[book]
authors = ["Miden contributors"]
description = "One stop shop for everything Miden"
language = "en"
multilingual = false
title = "The Miden book"

[output.html]
git-repository-url = "https://github.com/0xPolygonMiden/miden-docs"
no-section-label = true

[output.html.fold]
enable = true

[preprocessor.katex]
after = ["links"]

[preprocessor.alerts]

[output.linkcheck]
